// Word lists for Easy (4), Medium (5), Hard (6) difficulties
const WORDS_4 = [
    "able", "also", "area", "army", "away", "baby", "back", "ball", "band", "bank", "base", "bath", "bear", "beat", "been",
    "beer", "bell", "belt", "best", "bill", "bird", "blow", "blue", "boat", "body", "bomb", "bond", "bone", "book", "boom",
    "born", "boss", "both", "bowl", "bulk", "burn", "bush", "busy", "call", "calm", "came", "camp", "card", "care", "case",
    "cash", "cast", "cell", "cent", "chat", "chef", "chip", "city", "club", "coal", "coat", "code", "cold", "come", "cook",
    "cool", "cope", "copy", "core", "cost", "crew", "crop", "dark", "data", "date", "dawn", "dead", "deal", "dean", "dear",
    "debt", "deep", "deny", "desk", "dial", "diet", "disk", "does", "done", "door", "dose", "down", "draw", "drop", "drug",
    "dual", "duck", "duty", "earn", "ease", "east", "easy", "edge", "edit", "else", "even", "ever", "evil", "exit", "face",
    "fact", "fail", "fair", "fall", "fame", "farm", "fast", "fate", "fear", "feed", "feel", "feet", "fell", "felt", "file",
    "fill", "film", "find", "fine", "fire", "firm", "fish", "fist", "five", "flat", "flow", "fold", "folk", "food", "foot",
    "form", "fort", "foul", "four", "free", "from", "fuel", "full", "fund", "gain", "game", "gate", "gave", "gear", "gene",
    "gift", "girl", "give", "glad", "goal", "goes", "gold", "golf", "gone", "good", "grab", "gray", "grew", "grey", "grow",
    "gulf", "hair", "half", "hall", "hand", "hang", "hard", "harm", "hate", "have", "head", "heal", "hear", "heat", "help",
    "here", "hero", "hide", "high", "hill", "hire", "hold", "hole", "holy", "home", "hope", "host", "hour", "huge", "hung",
    "hunt", "hurt", "idea", "inch", "into", "iron", "item", "jack", "jail", "join", "jump", "jury", "just", "keep", "kept",
    "kick", "kill", "kind", "king", "knee", "knew", "know", "lack", "lady", "lake", "land", "last", "late", "lead", "left",
    "less", "life", "lift", "like", "line", "link", "list", "live", "load", "loan", "lock", "logo", "long", "look", "loop",
    "lose", "loss", "lost", "love", "luck", "made", "mail", "main", "make", "male", "mall", "many", "mark", "mass", "mate",
    "math", "meal", "mean", "meat", "meet", "menu", "mess", "mile", "milk", "mind", "mine", "miss", "mode", "mood", "moon",
    "more", "most", "move", "much", "must", "name", "navy", "near", "neck", "need", "news", "next", "nice", "nine", "node",
    "none", "nose", "note", "okay", "once", "only", "onto", "open", "oral", "over", "pace", "pack", "page", "paid", "pain",
    "pair", "palm", "park", "part", "pass", "past", "path", "peak", "pick", "pipe", "plan", "play", "plot", "plug", "plus",
    "poll", "pool", "poor", "port", "post", "pull", "pure", "push", "race", "rail", "rain", "rank", "rate", "read", "real",
    "rear", "rely", "rent", "rest", "rice", "rich", "ride", "ring", "rise", "risk", "road", "rock", "role", "roof", "room",
    "root", "rope", "rose", "rule", "rush", "safe", "said", "sake", "sale", "salt", "same", "sand", "save", "seat", "seed",
    "seek", "seem", "seen", "self", "sell", "send", "sent", "sept", "seth", "sexy", "ship", "shop", "shot", "show", "shut",
    "sick", "side", "sign", "site", "size", "skin", "slip", "slow", "snow", "soap", "soft", "soil", "sold", "sole", "some",
    "song", "soon", "sort", "soul", "spot", "star", "stay", "step", "stop", "suit",
    "sure", "take", "tale", "talk", "tall", "tank", "tape", "task", "team", "tech", "tell", "tend", "term", "test", "text",
    "than", "that", "them", "then", "they", "thin", "this", "thus", "tied", "time", "tiny", "told", "tone", "tool", "tour",
    "town", "trap", "tree", "trip", "true", "tune", "turn", "type", "unit", "upon", "urge", "used", "user", "uses", "vain",
    "vast", "very", "view", "vote", "wait", "wake", "walk", "wall", "want", "ward", "warm", "wash", "wave", "weak", "wear",
    "week", "well", "went", "were", "west", "what", "when", "whom", "wide", "wife", "wild", "will", "wind", "wine", "wing",
    "wish", "with", "wood", "word", "wore", "work", "yard", "yeah", "year", "your", "zero", "zone"
];

const WORDS_5 = [
    "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
    "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
    "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award", "aware",
    "badly", "baker", "bases", "basic", "basis", "beach", "began", "begin", "being", "below",
    "bench", "billy", "birth", "black", "blame", "blind", "block", "blood", "boost", "booth",
    "bound", "brain", "brake", "brand", "bread", "break", "breed", "brief", "bring", "broad", "broke",
    "brown", "build", "built", "buyer", "cable", "calif", "carry", "catch", "cause", "chain",
    "chair", "charm", "chart", "chase", "cheap", "check", "chest", "chief", "child", "china", "chose",
    "civil", "claim", "class", "clean", "clear", "click", "clock", "close", "coach", "coast",
    "could", "count", "court", "cover", "craft", "crash", "cream", "crime", "cross", "crowd",
    "crown", "crude", "carry", "curly", "curry", "curse", "curve", "cycle", "daily", "dance",
    "dated", "dealt", "death", "debut", "delay", "depth", "doing", "doubt", "dozen", "draft",
    "drama", "drank", "drawn", "dream", "dress", "drill", "drink", "drive", "drove", "dying",
    "eager", "early", "earth", "eight", "elite", "empty", "enemy", "enjoy", "enter", "entry",
    "equal", "error", "event", "every", "exact", "exist", "extra", "faith", "false", "fault",
    "fiber", "field", "fifth", "fifty", "fight", "final", "first", "fixed", "flash", "fleet",
    "floor", "fluid", "focus", "force", "forth", "forty", "forum", "found", "frame", "frank",
    "fraud", "fresh", "front", "fruit", "fully", "funny", "giant", "given", "glass", "globe",
    "going", "grace", "grade", "grand", "grant", "grass", "great", "green", "gross", "group",
    "grown", "guard", "guess", "guest", "guide", "happy", "harry", "heart", "heavy", "hence",
    "henry", "horse", "hotel", "house", "human", "ideal", "image", "index", "inner", "input",
    "issue", "japan", "jimmy", "joint", "jones", "judge", "known", "label", "large", "laser",
    "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal", "level", "lewis",
    "light", "limit", "links", "lives", "local", "loose", "lower", "lucky", "lunch", "lying",
    "magic", "major", "maker", "march", "maria", "match", "maybe", "mayor", "meant", "media",
    "metal", "might", "minor", "minus", "mixed", "model", "money", "month", "moral", "motor",
    "mount", "mouse", "mouth", "moved", "movie", "music", "needs", "never", "newly", "night",
    "noise", "north", "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "order",
    "other", "ought", "paint", "panel", "paper", "party", "peace", "peter", "phase", "phone",
    "photo", "piece", "pilot", "pitch", "place", "plain", "plane", "plant", "plate", "point",
    "pound", "power", "press", "price", "pride", "prime", "print", "prior", "prize", "proof",
    "proud", "prove", "queen", "quick", "quiet", "quite", "radio", "raise", "range", "rapid",
    "ratio", "reach", "ready", "realm", "rebel", "refer", "relax", "reply", "right", "rival",
    "river", "robin", "roger", "roman", "rough", "round", "route", "royal", "rural", "scale",
    "scene", "scope", "score", "sense", "serve", "seven", "shall", "shape", "share", "sharp",
    "sheet", "shelf", "shell", "shift", "shirt", "shock", "shoot", "short", "shown", "sight",
    "since", "sixth", "sixty", "sized", "skill", "sleep", "slide", "small", "smart", "smile",
    "smith", "smoke", "solid", "solve", "sorry", "sound", "south", "space", "spare", "speak",
    "speed", "spend", "spent", "split", "spoke", "sport", "staff", "stage", "stand", "start",
    "state", "steam", "steel", "steep", "steer", "steve", "stick", "still", "stock", "stone",
    "stood", "store", "storm", "story", "strip", "stuck", "study", "stuff", "style", "sugar",
    "suite", "super", "sweet", "table", "taken", "taste", "taxes", "teach", "teeth", "terry",
    "texas", "thank", "theft", "their", "theme", "there", "these", "thick", "thing", "think",
    "third", "those", "three", "threw", "throw", "thrown", "tight", "timed", "timer", "times",
    "tired", "title", "today", "topic", "total", "touch", "tough", "tower", "track", "trade",
    "train", "treat", "trend", "trial", "tribe", "trick", "tried", "tries", "truck", "truly",
    "trunk", "trust", "truth", "twice", "under", "undue", "union", "unity", "until", "upper",
    "upset", "urban", "usage", "usual", "valid", "value", "video", "virus", "visit", "vital",
    "vocal", "voice", "waste", "watch", "water", "wheel", "where", "which", "while", "white",
    "whole", "whose", "woman", "women", "world", "worry", "worse", "worst", "worth", "would",
    "wound", "write", "wrong", "wrote", "yield", "young", "youth"
];

const WORDS_6 = [
    "abroad", "accept", "access", "accord", "accuse", "across", "acting", "action", "active", "actual",
    "admire", "advice", "advise", "afford", "afraid", "agency", "agenda", "almost", "always", "amount",
    "animal", "annual", "answer", "anyone", "appeal", "appear", "artist", "aspect", "assign", "assist",
    "assume", "attack", "attend", "author", "backup", "battle", "beauty", "become", "before", "behalf",
    "behind", "belong", "better", "beyond", "bishop", "bitter", "border", "bottle", "bottom", "branch",
    "bright", "budget", "burden", "butter", "camera", "cannot", "career", "carpet", "casual", "caught",
    "center", "chance", "change", "charge", "choice", "choose", "circle", "client", "closet", "coffee",
    "coming", "commit", "common", "corner", "costly", "county", "course", "create", "credit", "custom",
    "damage", "danger", "dealer", "debate", "decade", "decide", "defeat", "defend", "define", "degree",
    "demand", "depend", "deploy", "design", "desire", "detail", "detect", "device", "direct", "doctor",
    "dollar", "donate", "double", "driver", "during", "easily", "eating", "effort", "either", "eleven",
    "emerge", "empire", "employ", "enable", "ending", "energy", "engage", "engine", "enough", "ensure",
    "entire", "escape", "estate", "ethics", "events", "excuse", "expand", "expect", "expert", "export",
    "extend", "fabric", "facing", "factor", "failed", "fairly", "family", "famous", "farmer", "faster",
    "father", "fellow", "female", "figure", "filter", "finger", "finish", "flight", "flower", "flying",
    "follow", "formal", "format", "former", "foster", "fought", "friend", "future", "garden", "gather",
    "gender", "gently", "global", "golden", "ground", "growth", "guilty", "handle", "happen", "hardly",
    "headed", "health", "height", "hidden", "highly", "hiring", "holder", "honest", "impact", "import",
    "income", "indeed", "injury", "inside", "intend", "intent", "invent", "invest", "island", "itself",
    "jacket", "junior", "keeper", "killer", "laptop", "larger", "latest", "launch", "lawyer", "leader",
    "league", "learns", "lesson", "letter", "liable", "likely", "listen", "little", "living", "lovers",
    "luxury", "making", "manage", "manual", "margin", "market", "master", "matter", "mature", "medium",
    "member", "memory", "mental", "method", "middle", "mirror", "mobile", "modern", "modest", "moment",
    "monkey", "mother", "motion", "movies", "murder", "museum", "mutual", "myself", "nation", "native",
    "nature", "nearby", "nearly", "nights", "nobody", "normal", "notice", "number", "object", "office",
    "online", "option", "orange", "origin", "output", "packet", "palace", "parent", "partly", "people",
    "period", "permit", "person", "phrase", "planet", "player", "please", "plenty", "pocket", "policy",
    "prefer", "pretty", "prince", "prison", "profit", "proper", "proven", "public", "puzzle", "random",
    "rarely", "rather", "rating", "reader", "really", "reason", "recall", "recent", "recipe", "record",
    "reduce", "reform", "regard", "region", "relate", "relief", "remote", "repair", "repeat", "report",
    "rescue", "resist", "resort", "result", "return", "reveal", "review", "reward", "rocket", "ruling",
    "runner", "safety", "salary", "sample", "saving", "school", "screen", "search", "season", "second",
    "secure", "select", "seller", "senior", "series", "server", "settle", "severe", "shadow", "shared",
    "should", "signal", "signed", "silent", "silver", "simple", "sister", "skills", "smooth", "social",
    "softer", "source", "speech", "spirit", "spoken", "spread", "spring", "stable", "stolen", "stored",
    "strain", "stream", "stress", "strict", "strike", "string", "strong", "studio", "submit", "sudden",
    "suffer", "summer", "supply", "surely", "survey", "switch", "symbol", "system", "taking", "talent",
    "target", "taught", "tenant", "thanks", "theory", "thirty", "though", "thread", "threat", "ticket",
    "timing", "tissue", "toward", "travel", "treaty", "trying", "tunnel", "twelve", "twenty", "unable",
    "unique", "united", "unless", "update", "useful", "valley", "value", "varied", "vendor", "verify",
    "versus", "victim", "vision", "visual", "voting", "waited", "walker", "wander", "wanted", "warmer",
    "wealth", "weekly", "weight", "window", "winner", "winter", "within", "wonder", "worker", "writer",
    "yellow"
];

// Make variables globally available
window.WORDS_4 = WORDS_4;
window.WORDS_5 = WORDS_5;
window.WORDS_6 = WORDS_6; 