/* words */
let words = [
  "about", "above", "abuse", "actor", "acute", "admit", "adopt", "adult", "after", "again",
    "agent", "agree", "ahead", "alarm", "album", "alert", "alike", "alive", "allow", "alone",
    "along", "alter", "among", "anger", "angle", "angry", "apart", "apple", "apply", "arena",
    "argue", "arise", "array", "aside", "asset", "audio", "audit", "avoid", "award", "aware",
    "badly", "baker", "bases", "basic", "basis", "beach", "began", "begin", "being", "below",
    "bench", "billy", "birth", "black", "blame", "blind", "block", "blood", "boost", "booth",
    "bound", "brain", "brake", "brand", "bread", "break", "breed", "brief", "bring", "broad", "broke",
    "brown", "build", "built", "buyer", "cable", "calif", "carry", "catch", "cause", "chain",
    "chair", "charm", "chart", "chase", "cheap", "check", "chest", "chief", "child", "china", "chose",
    "civil", "claim", "class", "clean", "clear", "click", "clock", "close", "coach", "coast",
    "could", "count", "court", "cover", "craft", "crash", "cream", "crime", "cross", "crowd",
    "crown", "crude", "carry", "curly", "curry", "curse", "curve", "cycle", "daily", "dance",
    "dated", "dealt", "death", "debut", "delay", "depth", "doing", "doubt", "dozen", "draft",
    "drama", "drank", "drawn", "dream", "dress", "drill", "drink", "drive", "drove", "dying",
    "eager", "early", "earth", "eight", "elite", "empty", "enemy", "enjoy", "enter", "entry",
    "equal", "error", "event", "every", "exact", "exist", "extra", "faith", "false", "fault",
    "fiber", "field", "fifth", "fifty", "fight", "final", "first", "fixed", "flash", "fleet",
    "floor", "fluid", "focus", "force", "forth", "forty", "forum", "found", "frame", "frank",
    "fraud", "fresh", "front", "fruit", "fully", "funny", "giant", "given", "glass", "globe",
    "going", "grace", "grade", "grand", "grant", "grass", "great", "green", "gross", "group",
    "grown", "guard", "guess", "guest", "guide", "happy", "harry", "heart", "heavy", "hence",
    "henry", "horse", "hotel", "house", "human", "ideal", "image", "index", "inner", "input",
    "issue", "japan", "jimmy", "joint", "jones", "judge", "known", "label", "large", "laser",
    "later", "laugh", "layer", "learn", "lease", "least", "leave", "legal", "level", "lewis",
    "light", "limit", "links", "lives", "local", "loose", "lower", "lucky", "lunch", "lying",
    "magic", "major", "maker", "march", "maria", "match", "maybe", "mayor", "meant", "media",
    "metal", "might", "minor", "minus", "mixed", "model", "money", "month", "moral", "motor",
    "mount", "mouse", "mouth", "moved", "movie", "music", "needs", "never", "newly", "night",
    "noise", "north", "noted", "novel", "nurse", "occur", "ocean", "offer", "often", "order",
    "other", "ought", "paint", "panel", "paper", "party", "peace", "peter", "phase", "phone",
    "photo", "piece", "pilot", "pitch", "place", "plain", "plane", "plant", "plate", "point",
    "pound", "power", "press", "price", "pride", "prime", "print", "prior", "prize", "proof",
    "proud", "prove", "queen", "quick", "quiet", "quite", "radio", "raise", "range", "rapid",
    "ratio", "reach", "ready", "realm", "rebel", "refer", "relax", "reply", "right", "rival",
    "river", "robin", "roger", "roman", "rough", "round", "route", "royal", "rural", "scale",
    "scene", "scope", "score", "sense", "serve", "seven", "shall", "shape", "share", "sharp",
    "sheet", "shelf", "shell", "shift", "shirt", "shock", "shoot", "short", "shown", "sight",
    "since", "sixth", "sixty", "sized", "skill", "sleep", "slide", "small", "smart", "smile",
    "smith", "smoke", "solid", "solve", "sorry", "sound", "south", "space", "spare", "speak",
    "speed", "spend", "spent", "split", "spoke", "sport", "staff", "stage", "stand", "start",
    "state", "steam", "steel", "steep", "steer", "steve", "stick", "still", "stock", "stone",
    "stood", "store", "storm", "story", "strip", "stuck", "study", "stuff", "style", "sugar",
    "suite", "super", "sweet", "table", "taken", "taste", "taxes", "teach", "teeth", "terry",
    "texas", "thank", "theft", "their", "theme", "there", "these", "thick", "thing", "think",
    "third", "those", "three", "threw", "throw", "thrown", "tight", "timed", "timer", "times",
    "tired", "title", "today", "topic", "total", "touch", "tough", "tower", "track", "trade",
    "train", "treat", "trend", "trial", "tribe", "trick", "tried", "tries", "truck", "truly",
    "trunk", "trust", "truth", "twice", "under", "undue", "union", "unity", "until", "upper",
    "upset", "urban", "usage", "usual", "valid", "value", "video", "virus", "visit", "vital",
    "vocal", "voice", "waste", "watch", "water", "wheel", "where", "which", "while", "white",
    "whole", "whose", "woman", "women", "world", "worry", "worse", "worst", "worth", "would",
    "wound", "write", "wrong", "wrote", "yield", "young", "youth"
];

/* Word clues dictionary */
let clues = {
  "about": "Approximately or concerning",
  "above": "Higher than or overhead",
  "abuse": "Misuse or mistreat",
  "actor": "One who performs in plays or films",
  "acute": "Sharp or severe",
  "admit": "Confess or allow entry",
  "adopt": "Take in as one's own",
  "adult": "Grown-up person",
  "after": "Following in time",
  "again": "Once more",
  "agent": "Representative or spy",
  "agree": "Share the same opinion",
  "ahead": "In front or in advance",
  "alarm": "Warning device or fear",
  "album": "Collection of photos or songs",
  "alert": "Watchful or warning signal",
  "alike": "Similar or the same",
  "alive": "Living or animated",
  "allow": "Permit or let happen",
  "alone": "By oneself",
  "along": "Moving forward or beside",
  "alter": "Change or modify",
  "among": "In the middle of several",
  "anger": "Strong displeasure",
  "angle": "Corner or point of view",
  "angry": "Mad or upset",
  "apart": "Separated or away from",
  "apple": "Common red or green fruit",
  "apply": "Put to use or request formally",
  "arena": "Stadium or area of conflict",
  "argue": "Debate or quarrel",
  "arise": "Get up or come into being",
  "array": "Ordered arrangement",
  "aside": "To the side or apart",
  "asset": "Valuable resource",
  "audio": "Sound recording",
  "audit": "Formal examination of accounts",
  "avoid": "Stay away from",
  "award": "Prize or honor",
  "aware": "Conscious of something",
  "badly": "In a poor manner",
  "baker": "One who makes bread",
  "bases": "Foundations or home plates",
  "basic": "Fundamental or simple",
  "basis": "Foundation or starting point",
  "beach": "Sandy shore",
  "began": "Started (past tense)",
  "begin": "Start or commence",
  "being": "Existence or creature",
  "below": "Underneath or lower than",
  "bench": "Long seat or judge's seat",
  "billy": "Common male nickname",
  "birth": "Beginning of life",
  "black": "Darkest color",
  "blame": "Hold responsible",
  "blind": "Unable to see",
  "block": "Solid piece or obstruct",
  "blood": "Red fluid in veins",
  "boost": "Increase or lift up",
  "booth": "Small enclosed space",
  "bound": "Tied up or heading toward",
  "brain": "Organ of thought",
  "brake": "Device to slow or stop",
  "brand": "Make or trademark",
  "bread": "Baked staple food",
  "break": "Separate into pieces",
  "breed": "Raise animals or type",
  "brief": "Short or concise",
  "bring": "Carry to a place",
  "broad": "Wide or extensive",
  "broke": "Penniless or damaged",
  "brown": "Color of wood",
  "build": "Construct or create",
  "built": "Constructed (past tense)",
  "buyer": "One who purchases",
  "cable": "Thick rope or wire",
  "calif": "Short for California",
  "carry": "Transport or bear",
  "catch": "Capture or grab",
  "cause": "Reason or make happen",
  "chain": "Connected metal links",
  "chair": "Seat with back",
  "charm": "Appeal or magic spell",
  "chart": "Graph or map",
  "chase": "Pursue or run after",
  "cheap": "Inexpensive or low quality",
  "check": "Verify or bank draft",
  "chest": "Torso or storage box",
  "chief": "Leader or main",
  "child": "Young person",
  "china": "Asian country or porcelain",
  "chose": "Selected (past tense)",
  "civil": "Relating to citizens or polite",
  "claim": "Assert or demand",
  "class": "Group or category",
  "clean": "Free from dirt",
  "clear": "Transparent or obvious",
  "click": "Short sharp sound",
  "clock": "Time-telling device",
  "close": "Near or shut",
  "coach": "Trainer or bus",
  "coast": "Shoreline or glide",
  "could": "Past tense of can",
  "count": "Number or nobleman",
  "court": "Legal venue or woo",
  "cover": "Place over or conceal",
  "craft": "Skill or vessel",
  "crash": "Violent collision",
  "cream": "Dairy product or best part",
  "crime": "Illegal act",
  "cross": "Intersect or religious symbol",
  "crowd": "Large group of people",
  "crown": "Royal headpiece",
  "crude": "Raw or unrefined",
  "curly": "Having curves or spirals",
  "curry": "Spiced dish",
  "curse": "Evil spell or swear",
  "curve": "Bend or arc",
  "cycle": "Series or bicycle",
  "daily": "Every day",
  "dance": "Move to music",
  "dated": "Showed age or went out with",
  "dealt": "Distributed cards or handled",
  "death": "End of life",
  "debut": "First appearance",
  "delay": "Postpone or wait",
  "depth": "Distance downward",
  "doing": "Performing actions",
  "doubt": "Uncertainty or question",
  "dozen": "Group of twelve",
  "draft": "Preliminary version or breeze",
  "drama": "Play or emotional situation",
  "drank": "Consumed liquid (past)",
  "drawn": "Pulled or sketched",
  "dream": "Sleep vision or aspiration",
  "dress": "Garment or prepare",
  "drill": "Boring tool or practice",
  "drink": "Consume liquid",
  "drive": "Operate vehicle or motivation",
  "drove": "Operated vehicle (past)",
  "dying": "Near death or fading",
  "eager": "Enthusiastic or keen",
  "early": "Before expected time",
  "earth": "Our planet or soil",
  "eight": "Number after seven",
  "elite": "Best or select group",
  "empty": "Containing nothing",
  "enemy": "Opponent or foe",
  "enjoy": "Take pleasure in",
  "enter": "Go into or join",
  "entry": "Way in or submission",
  "equal": "Same in value",
  "error": "Mistake or fault",
  "event": "Happening or occasion",
  "every": "Each without exception",
  "exact": "Precise or demand",
  "exist": "Be present or live",
  "extra": "Additional or beyond",
  "faith": "Trust or belief system",
  "false": "Not true or fake",
  "fault": "Defect or blame",
  "fiber": "Thread or dietary roughage",
  "field": "Open land or area of study",
  "fifth": "Ordinal number 5",
  "fifty": "Number after forty-nine",
  "fight": "Physical combat or struggle",
  "final": "Last or ultimate",
  "first": "Before all others",
  "fixed": "Repaired or set",
  "flash": "Brief burst of light",
  "fleet": "Group of ships or fast",
  "floor": "Bottom surface of room",
  "fluid": "Flowing liquid",
  "focus": "Center of attention",
  "force": "Power or compel",
  "forth": "Forward or onward",
  "forty": "Number before forty-one",
  "forum": "Public meeting place",
  "found": "Discovered or established",
  "frame": "Border or structure",
  "frank": "Honest or hot dog",
  "fraud": "Deception for gain",
  "fresh": "New or not stale",
  "front": "Forward part or facade",
  "fruit": "Sweet plant product",
  "fully": "Completely or entirely",
  "funny": "Amusing or strange",
  "giant": "Very large being",
  "given": "Granted or specified",
  "glass": "Transparent material",
  "globe": "Sphere or Earth",
  "going": "Moving or leaving",
  "grace": "Elegance or blessing",
  "grade": "Level or evaluate",
  "grand": "Impressive or thousand",
  "grant": "Give or allow",
  "grass": "Green ground cover",
  "great": "Very good or large",
  "green": "Color of grass",
  "gross": "Total or disgusting",
  "group": "Collection of things",
  "grown": "Matured or cultivated",
  "guard": "Protect or watchman",
  "guess": "Estimate without certainty",
  "guest": "Visitor or invitee",
  "guide": "Lead or instruction book",
  "happy": "Feeling joy",
  "harry": "Male name or harass",
  "heart": "Organ that pumps blood",
  "heavy": "Weighing much",
  "hence": "Therefore or from now",
  "henry": "Male name or unit",
  "horse": "Large riding animal",
  "hotel": "Lodging establishment",
  "house": "Dwelling or shelter",
  "human": "Person or relating to people",
  "ideal": "Perfect or standard",
  "image": "Picture or representation",
  "index": "List or pointer",
  "inner": "Interior or private",
  "input": "Data entered or contribution",
  "issue": "Problem or edition",
  "japan": "Asian island nation",
  "jimmy": "Male nickname or pry open",
  "joint": "Connection or shared",
  "jones": "Common surname",
  "judge": "Court official or evaluate",
  "known": "Recognized or familiar",
  "label": "Tag or classify",
  "large": "Big in size",
  "laser": "Focused light beam",
  "later": "Afterward or subsequent",
  "laugh": "Express amusement",
  "layer": "Level or coating",
  "learn": "Gain knowledge",
  "lease": "Rental agreement",
  "least": "Smallest amount",
  "leave": "Depart or permission",
  "legal": "Lawful or permitted",
  "level": "Flat or degree",
  "lewis": "Male name",
  "light": "Illumination or not heavy",
  "limit": "Boundary or restrict",
  "links": "Connections or golf course",
  "lives": "Exists or plural of life",
  "local": "Nearby or resident",
  "loose": "Not tight or free",
  "lower": "Move down or beneath",
  "lucky": "Fortunate or blessed",
  "lunch": "Midday meal",
  "lying": "Reclining or not truthful",
  "magic": "Illusion or supernatural",
  "major": "Important or military rank",
  "maker": "Creator or manufacturer",
  "march": "Walk in formation or month",
  "maria": "Female name",
  "match": "Contest or correspond",
  "maybe": "Perhaps or possibly",
  "mayor": "City leader",
  "meant": "Intended or signified",
  "media": "Communication channels",
  "metal": "Hard shiny element",
  "might": "Power or possibility",
  "minor": "Small or underage person",
  "minus": "Subtraction sign or negative",
  "mixed": "Combined or blended",
  "model": "Example or pose",
  "money": "Currency or wealth",
  "month": "Division of year",
  "moral": "Ethical or lesson",
  "motor": "Engine or drive",
  "mount": "Climb or horse",
  "mouse": "Small rodent or computer device",
  "mouth": "Oral opening",
  "moved": "Changed position or touched emotionally",
  "movie": "Motion picture or film",
  "music": "Organized sound or melody",
  "needs": "Requires or necessities",
  "never": "Not ever or at no time",
  "newly": "Recently or freshly",
  "night": "Dark hours after sunset",
  "noise": "Unwanted sound",
  "north": "Cardinal direction or upward",
  "noted": "Famous or observed",
  "novel": "Book or new",
  "nurse": "Medical caregiver",
  "occur": "Happen or take place",
  "ocean": "Large body of saltwater",
  "offer": "Present for acceptance",
  "often": "Frequently or many times",
  "order": "Sequence or command",
  "other": "Different or additional",
  "ought": "Should or moral duty",
  "paint": "Colored coating",
  "panel": "Flat board or group",
  "paper": "Writing material",
  "party": "Social gathering or political group",
  "peace": "Absence of war or calm",
  "peter": "Male name",
  "phase": "Stage or aspect",
  "phone": "Communication device",
  "photo": "Photograph or picture",
  "piece": "Part or portion",
  "pilot": "Aircraft operator",
  "pitch": "Throw or musical tone",
  "place": "Location or position",
  "plain": "Simple or flat land",
  "plane": "Aircraft or flat surface",
  "plant": "Living organism or factory",
  "plate": "Flat dish or sheet",
  "point": "Sharp end or purpose",
  "pound": "Unit of weight or strike",
  "power": "Strength or authority",
  "press": "Push or news media",
  "price": "Cost or value",
  "pride": "Satisfaction or lion group",
  "prime": "Best quality or first",
  "print": "Produce text or mark",
  "prior": "Earlier or before",
  "prize": "Award or value highly",
  "proof": "Evidence or verification",
  "proud": "Feeling satisfaction",
  "prove": "Demonstrate truth",
  "queen": "Female monarch",
  "quick": "Fast or rapid",
  "quiet": "Silent or peaceful",
  "quite": "Rather or completely",
  "radio": "Broadcast medium",
  "raise": "Lift up or increase",
  "range": "Extent or series",
  "rapid": "Very fast or swift",
  "ratio": "Proportion or relationship",
  "reach": "Extend to or arrive at",
  "ready": "Prepared or willing",
  "realm": "Kingdom or domain",
  "rebel": "Resist authority",
  "refer": "Direct attention or mention",
  "relax": "Rest or become less tense",
  "reply": "Respond or answer",
  "right": "Correct or opposite of left",
  "rival": "Competitor or opponent",
  "river": "Large flowing stream",
  "robin": "Red-breasted bird or name",
  "roger": "Male name or radio affirmative",
  "roman": "From Rome or typeface",
  "rough": "Not smooth or approximate",
  "round": "Circular or series",
  "route": "Path or way",
  "royal": "Relating to monarchy",
  "rural": "Country or agricultural",
  "scale": "Measure or climb",
  "scene": "Location of action or view",
  "scope": "Extent or viewing device",
  "score": "Points earned or twenty",
  "sense": "Perception or meaning",
  "serve": "Work for or provide",
  "seven": "Number after six",
  "shall": "Will or must",
  "shape": "Form or condition",
  "share": "Divide among or portion",
  "sharp": "Having keen edge",
  "sheet": "Flat piece or bed linen",
  "shelf": "Horizontal storage surface",
  "shell": "Hard outer covering",
  "shift": "Move or work period",
  "shirt": "Upper body garment",
  "shock": "Sudden impact or surprise",
  "shoot": "Fire weapon or photograph",
  "short": "Not long or brief",
  "shown": "Displayed or demonstrated",
  "sight": "Vision or view",
  "since": "From then until now",
  "sixth": "Ordinal number 6",
  "sixty": "Number after fifty-nine",
  "sized": "Having particular dimensions",
  "skill": "Ability or expertise",
  "sleep": "Rest with closed eyes",
  "slide": "Glide smoothly or playground item",
  "small": "Little in size",
  "smart": "Intelligent or stylish",
  "smile": "Happy facial expression",
  "smith": "Metalworker or common surname",
  "smoke": "Visible vapor from fire",
  "solid": "Firm or reliable",
  "solve": "Find answer to",
  "sorry": "Feeling regret",
  "sound": "Noise or healthy",
  "south": "Cardinal direction or downward",
  "space": "Empty area or cosmos",
  "spare": "Extra or show mercy",
  "speak": "Talk or communicate",
  "speed": "Rate of motion",
  "spend": "Use money or pass time",
  "spent": "Used up or exhausted",
  "split": "Divide or separate",
  "spoke": "Said or wheel rod",
  "sport": "Athletic game",
  "staff": "Employees or stick",
  "stage": "Platform or phase",
  "stand": "Be upright or tolerate",
  "start": "Begin or initial movement",
  "state": "Condition or government division",
  "steam": "Water vapor or power",
  "steel": "Strong metal alloy",
  "steep": "Sharp incline",
  "steer": "Guide or young bull",
  "steve": "Male name",
  "stick": "Rod or adhere",
  "still": "Motionless or yet",
  "stock": "Supply or shares",
  "stone": "Rock or hard pit",
  "stood": "Was upright (past)",
  "store": "Shop or save for later",
  "storm": "Violent weather",
  "story": "Tale or building level",
  "strip": "Remove or narrow piece",
  "stuck": "Unable to move",
  "study": "Learn or research",
  "stuff": "Things or fill",
  "style": "Manner or fashion",
  "sugar": "Sweet substance",
  "suite": "Set of rooms or group",
  "super": "Excellent or above",
  "sweet": "Sugary taste or kind",
  "table": "Furniture with flat top",
  "taken": "Seized or occupied",
  "taste": "Flavor sense or sample",
  "taxes": "Government levies",
  "teach": "Instruct or educate",
  "teeth": "Plural of tooth",
  "terry": "Male name or fabric",
  "texas": "Large US state",
  "thank": "Express gratitude",
  "theft": "Act of stealing",
  "their": "Belonging to them",
  "theme": "Subject or motif",
  "there": "In that place",
  "these": "Plural of this",
  "thick": "Wide or dense",
  "thing": "Object or matter",
  "think": "Use mind or believe",
  "third": "Ordinal number 3",
  "those": "Plural of that",
  "three": "Number after two",
  "threw": "Tossed (past tense)",
  "throw": "Toss or hurl",
  "thrown": "Tossed (past participle)",
  "tight": "Firmly fixed or tense",
  "timed": "Measured duration",
  "timer": "Time-measuring device",
  "times": "Occasions or multiplied by",
  "tired": "Needing rest or weary",
  "title": "Name or heading",
  "today": "This present day",
  "topic": "Subject of discussion",
  "total": "Complete sum",
  "touch": "Make contact or affect",
  "tough": "Strong or difficult",
  "tower": "Tall structure",
  "track": "Path or follow",
  "trade": "Exchange or profession",
  "train": "Teach or linked cars",
  "treat": "Deal with or special food",
  "trend": "General direction or fashion",
  "trial": "Court proceeding or test",
  "tribe": "Social group or family",
  "trick": "Deceive or clever act",
  "tried": "Attempted or tested",
  "tries": "Attempts or efforts",
  "truck": "Large vehicle",
  "truly": "Genuinely or really",
  "trunk": "Tree body or large box",
  "trust": "Confidence or rely on",
  "truth": "What is factual",
  "twice": "Two times",
  "under": "Below or beneath",
  "undue": "Excessive or improper",
  "union": "Joining or labor organization",
  "unity": "Oneness or harmony",
  "until": "Up to the time",
  "upper": "Higher in position",
  "upset": "Distressed or overturn",
  "urban": "City or metropolitan",
  "usage": "Way of using",
  "usual": "Normal or customary",
  "valid": "Acceptable or sound",
  "value": "Worth or importance",
  "video": "Moving pictures",
  "virus": "Infectious agent",
  "visit": "Go to see",
  "vital": "Essential or crucial",
  "vocal": "Relating to voice or outspoken",
  "voice": "Sound from mouth",
  "waste": "Squander or garbage",
  "watch": "Observe or timepiece",
  "water": "Clear liquid essential for life",
  "wheel": "Circular rotating object",
  "where": "At what place",
  "which": "What one or ones",
  "while": "During the time",
  "white": "Lightest color",
  "whole": "Complete or entire",
  "whose": "Belonging to whom",
  "woman": "Adult female",
  "women": "Plural of woman",
  "world": "Earth or society",
  "worry": "Feel anxious",
  "worse": "More bad or inferior",
  "worst": "Most bad or least good",
  "worth": "Value or deserving",
  "would": "Past of will or conditional",
  "wound": "Injury or coiled",
  "write": "Put words on paper",
  "wrong": "Incorrect or immoral",
  "wrote": "Put in writing (past)",
  "yield": "Produce or give way",
  "young": "Not old or youthful",
  "youth": "Early life or young people"
};