name: Deploy Driving Simulator

on:
  push:
    branches: [ main ]
    paths: [ 'Driving-Sim/**' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: |
        npm install -g replace-in-file
        
    - name: Inject Mapbox token
      run: |
        replace-in-file \
          --configFile=replace-config.js \
          --replace="mapboxgl.accessToken = '${{ secrets.MAPBOX_ACCESS_TOKEN }}';" \
          --path=Driving-Sim/script.js \
          --match="mapboxgl.accessToken = '';"
      env:
        MAPBOX_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./Driving-Sim
        destination_dir: driving-sim
